#! python3
import re, pyperclip

phoneRegex = re.compile(r'''
# 000-000-0000, 000-0000, (000) 000-000, 000-0000 ext 00000, ext., x00000

(
((\d\d\d) | (\(\d\d\d\)))?        # area code?
(\s | - |.)        # first separator
\d\d\d        # first 2 digits
(- |.)        # second separator
\d\d\d\d        # last 4 digits
(((ext(\.)?\s) |x)        # extension word?
(\d{2,5}))?   # extension number?
)
''', re.VERBOSE)


emailRegex = re.compile(r'''
# some.+_thing@(\d{2,5}))?.com

[a-zA-Z0-9_.+]+    # name part
@      # @ symbol
[a-zA-Z0-9_.+]+    # domain name part

''', re.VERBOSE)

text = pyperclip.paste()


extractedPhone = phoneRegex.findall(text)
extractedEmail = emailRegex.findall(text)

allPhoneNumbers = []
for phoneNumber in extractedPhone:
    allPhoneNumbers.append(phoneNumber[0])

print(allPhoneNumbers)
print(extractedEmail)

results = '\n'.join(allPhoneNumbers) + '\n' + '\n'.join(extractedEmail)
pyperclip.copy(results)
